-- Migration: extend task_runs.status ENUM to include skip variants
ALTER TABLE task_runs MODIFY status ENUM(
  'SCHEDULED','RUNNING','SUCCESS','FAILED','TIMEOUT','RETRYING','CALLBACK_PENDING','CALLBACK_SUCCESS','FAILED_TIMEOUT','CANCELED','SKIPPED',
  'FAILURE_SKIP','CONCURRENT_SKIP','OVERLAP_SKIP'
) NOT NULL DEFAULT 'SCHEDULED';

