-- Migration: add CALLBACK_FAILED to task_runs.status enum
ALTER TABLE task_runs MODIFY status ENUM(
  'SCHEDULED','RUNNING','SUCCESS','FAILED','TIMEOUT','RETRYING','CALLBACK_PENDING','CALLBACK_SUCCESS','CALLBACK_FAILED','FAILED_TIMEOUT','CANCELED','SKIPPED',
  'FAILURE_SKIP','CONCURRENT_SKIP','OVERLAP_SKIP'
) NOT NULL DEFAULT 'SCHEDULED';

