"""BI metric definitions (preserved from old bi_engine)."""
from __future__ import annotations

from typing import Any, Dict, List


METRIC_DEFINITIONS: List[Dict[str, Any]] = [
    {
        "code": "revenue_total",
        "label": "营业总收入",
        "category": "profitability",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "TOT_OPERA_REV",
        "source_fields": ["income.TOT_OPERA_REV"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "operating_profit",
        "label": "营业利润",
        "category": "profitability",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "OPERA_PROFIT",
        "source_fields": ["income.OPERA_PROFIT"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "net_profit_parent",
        "label": "归母净利润",
        "category": "profitability",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "NET_PRO_EXCL_MIN_INT_INC",
        "source_fields": ["income.NET_PRO_EXCL_MIN_INT_INC"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "operating_cashflow",
        "label": "经营现金流净额",
        "category": "cashflow",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "NET_CASH_FLOW_OPERA_ACT",
        "source_fields": ["cashflow.NET_CASH_FLOW_OPERA_ACT"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "total_assets",
        "label": "总资产",
        "category": "balance",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "TOTAL_ASSETS",
        "source_fields": ["balance_sheet.TOTAL_ASSETS"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "total_liab",
        "label": "总负债",
        "category": "balance",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "TOTAL_LIAB",
        "source_fields": ["balance_sheet.TOTAL_LIAB"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "equity_parent",
        "label": "归母权益",
        "category": "balance",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "TOT_SHARE_EQUITY_EXCL_MIN_INT",
        "source_fields": ["balance_sheet.TOT_SHARE_EQUITY_EXCL_MIN_INT"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "debt_ratio",
        "label": "资产负债率",
        "category": "solvency",
        "display_kind": "pct_point",
        "unit": "ratio",
        "formula": "TOTAL_LIAB / TOTAL_ASSETS",
        "source_fields": ["balance_sheet.TOTAL_LIAB", "balance_sheet.TOTAL_ASSETS"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "current_ratio",
        "label": "流动比率",
        "category": "solvency",
        "display_kind": "ratio",
        "unit": "ratio",
        "formula": "TOTAL_CUR_ASSETS / TOTAL_CUR_LIAB",
        "source_fields": ["balance_sheet.TOTAL_CUR_ASSETS", "balance_sheet.TOTAL_CUR_LIAB"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "quick_ratio",
        "label": "速动比率",
        "category": "solvency",
        "display_kind": "ratio",
        "unit": "ratio",
        "formula": "(TOTAL_CUR_ASSETS - INV) / TOTAL_CUR_LIAB",
        "source_fields": ["balance_sheet.TOTAL_CUR_ASSETS", "balance_sheet.TOTAL_CUR_LIAB", "balance_sheet.INV"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "roe",
        "label": "ROE",
        "category": "profitability",
        "display_kind": "pct_point",
        "unit": "ratio",
        "formula": "NET_PRO_EXCL_MIN_INT_INC / AVG(TOT_SHARE_EQUITY_EXCL_MIN_INT)",
        "source_fields": ["income.NET_PRO_EXCL_MIN_INT_INC", "balance_sheet.TOT_SHARE_EQUITY_EXCL_MIN_INT"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "roa",
        "label": "ROA",
        "category": "profitability",
        "display_kind": "pct_point",
        "unit": "ratio",
        "formula": "NET_PRO_EXCL_MIN_INT_INC / AVG(TOTAL_ASSETS)",
        "source_fields": ["income.NET_PRO_EXCL_MIN_INT_INC", "balance_sheet.TOTAL_ASSETS"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "net_margin",
        "label": "净利率",
        "category": "profitability",
        "display_kind": "pct_point",
        "unit": "ratio",
        "formula": "NET_PRO_EXCL_MIN_INT_INC / TOT_OPERA_REV",
        "source_fields": ["income.NET_PRO_EXCL_MIN_INT_INC", "income.TOT_OPERA_REV"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "operating_profit_margin",
        "label": "营业利润率",
        "category": "profitability",
        "display_kind": "pct_point",
        "unit": "ratio",
        "formula": "OPERA_PROFIT / TOT_OPERA_REV",
        "source_fields": ["income.OPERA_PROFIT", "income.TOT_OPERA_REV"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "asset_turnover",
        "label": "总资产周转率",
        "category": "efficiency",
        "display_kind": "ratio",
        "unit": "ratio",
        "formula": "TOT_OPERA_REV / AVG(TOTAL_ASSETS)",
        "source_fields": ["income.TOT_OPERA_REV", "balance_sheet.TOTAL_ASSETS"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "ar_turnover",
        "label": "应收账款周转率",
        "category": "efficiency",
        "display_kind": "ratio",
        "unit": "ratio",
        "formula": "TOT_OPERA_REV / AVG(ACCT_RECEIVABLE)",
        "source_fields": ["income.TOT_OPERA_REV", "balance_sheet.ACCT_RECEIVABLE"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "inventory_turnover",
        "label": "存货周转率",
        "category": "efficiency",
        "display_kind": "ratio",
        "unit": "ratio",
        "formula": "LESS_OPERA_COST / AVG(INV)",
        "source_fields": ["income.LESS_OPERA_COST", "balance_sheet.INV"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "ocf_to_profit",
        "label": "OCF/净利润",
        "category": "cashflow",
        "display_kind": "ratio",
        "unit": "ratio",
        "formula": "NET_CASH_FLOW_OPERA_ACT / NET_PRO_EXCL_MIN_INT_INC",
        "source_fields": ["cashflow.NET_CASH_FLOW_OPERA_ACT", "income.NET_PRO_EXCL_MIN_INT_INC"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "ocf_to_revenue",
        "label": "OCF/营业收入",
        "category": "cashflow",
        "display_kind": "ratio",
        "unit": "ratio",
        "formula": "NET_CASH_FLOW_OPERA_ACT / TOT_OPERA_REV",
        "source_fields": ["cashflow.NET_CASH_FLOW_OPERA_ACT", "income.TOT_OPERA_REV"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "free_cash_flow",
        "label": "自由现金流",
        "category": "cashflow",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "FREE_CASH_FLOW",
        "source_fields": ["cashflow.FREE_CASH_FLOW"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "period_expense_ratio",
        "label": "期间费用率",
        "category": "profitability",
        "display_kind": "pct_point",
        "unit": "ratio",
        "formula": "(LESS_SELLING_EXP + LESS_ADMIN_EXP + LESS_FIN_EXP) / TOT_OPERA_REV",
        "source_fields": [
            "income.LESS_SELLING_EXP",
            "income.LESS_ADMIN_EXP",
            "income.LESS_FIN_EXP",
            "income.TOT_OPERA_REV",
        ],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "rd_expense_ratio",
        "label": "研发费用率",
        "category": "profitability",
        "display_kind": "pct_point",
        "unit": "ratio",
        "formula": "RD_EXP / TOT_OPERA_REV",
        "source_fields": ["income.RD_EXP", "income.TOT_OPERA_REV"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "equity_multiplier",
        "label": "权益乘数",
        "category": "dupont",
        "display_kind": "ratio",
        "unit": "ratio",
        "formula": "AVG(TOTAL_ASSETS) / AVG(TOT_SHARE_EQUITY_EXCL_MIN_INT)",
        "source_fields": ["balance_sheet.TOTAL_ASSETS", "balance_sheet.TOT_SHARE_EQUITY_EXCL_MIN_INT"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "currency_cap",
        "label": "货币资金",
        "category": "solvency",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "CURRENCY_CAP",
        "source_fields": ["balance_sheet.CURRENCY_CAP"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "short_borrowing",
        "label": "短期借款",
        "category": "solvency",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "ST_BORROWING",
        "source_fields": ["balance_sheet.ST_BORROWING"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "long_term_loan",
        "label": "长期借款",
        "category": "solvency",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "LT_LOAN",
        "source_fields": ["balance_sheet.LT_LOAN"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
    {
        "code": "bonds_payable",
        "label": "应付债券",
        "category": "solvency",
        "display_kind": "amount",
        "unit": "亿元",
        "formula": "BONDS_PAYABLE",
        "source_fields": ["balance_sheet.BONDS_PAYABLE"],
        "applicable_comp_types": [1],
        "phase": "phase1",
        "available": True,
    },
]
