from enum import Enum
class TaskCode(str, Enum):
    STOCK_ZH_A_LIST = 'STOCK_ZH_A_LIST'
    STOCK_ZH_A_HIST_PARENT = 'STOCK_ZH_A_HIST_PARENT'
    STOCK_ZH_A_HIST_CHILD = 'STOCK_ZH_A_HIST_CHILD'
    STOCK_ZH_A_MKT_CATEGORY = 'STOCK_ZH_A_MKT_CATEGORY'
    STOCK_ZH_A_MKT_CATEGORY_SWHY = 'STOCK_ZH_A_MKT_CATEGORY_SWHY'
    STOCK_ZH_A_INDUSTRY_CONSTITUENT_SWHY = 'STOCK_ZH_A_INDUSTRY_CONSTITUENT_SWHY'
    STOCK_ZH_A_INDUSTRY_WEIGHT_SWHY = 'STOCK_ZH_A_INDUSTRY_WEIGHT_SWHY'
    STOCK_ZH_A_INDUSTRY_DAILY_SWHY = 'STOCK_ZH_A_INDUSTRY_DAILY_SWHY'
    BACKTRADER_CAMPAIGN = 'BACKTRADER_CAMPAIGN'
    BACKTRADER_RUN = 'BACKTRADER_RUN'
