
TASK_FREQUENCY_MIN1 = "1m"
TASK_FREQUENCY_MIN15 = "15m"
TASK_FREQUENCY_MIN30 = "30m"
TASK_FREQUENCY_HOURLY = "hourly"
TASK_FREQUENCY_DAILY = "daily"
TASK_FREQUENCY_WEEKLY = "weekly"
TASK_FREQUENCY_MONTHLY = "monthly"

ADJUST_NONE = "nf"
ADJUST_FORWARD = "qfq"
ADJUST_BACKWARD = "hfq"
ADJUST_BACKWORD = ADJUST_BACKWARD
