from __future__ import annotations


# bond_zh_us_rate has no separate instrument-list endpoint. These definitions
# describe every value column exposed by that API; they are registry identities,
# not a download whitelist.
RATE_SERIES = (
    {
        "symbol": "CN_GOVT_2Y",
        "name": "中国国债收益率2年",
        "source_field": "中国国债收益率2年",
        "exchange": "CN",
        "observation_type": "bond_yield",
        "unit": "percent",
    },
    {
        "symbol": "CN_GOVT_5Y",
        "name": "中国国债收益率5年",
        "source_field": "中国国债收益率5年",
        "exchange": "CN",
        "observation_type": "bond_yield",
        "unit": "percent",
    },
    {
        "symbol": "CN_GOVT_10Y",
        "name": "中国国债收益率10年",
        "source_field": "中国国债收益率10年",
        "exchange": "CN",
        "observation_type": "bond_yield",
        "unit": "percent",
    },
    {
        "symbol": "CN_GOVT_30Y",
        "name": "中国国债收益率30年",
        "source_field": "中国国债收益率30年",
        "exchange": "CN",
        "observation_type": "bond_yield",
        "unit": "percent",
    },
    {
        "symbol": "CN_GOVT_10Y_2Y",
        "name": "中国国债收益率10年-2年",
        "source_field": "中国国债收益率10年-2年",
        "exchange": "CN",
        "observation_type": "yield_spread",
        "unit": "percentage_point",
    },
    {
        "symbol": "CN_GDP_YOY",
        "name": "中国GDP年增率",
        "source_field": "中国GDP年增率",
        "exchange": "CN",
        "observation_type": "gdp_yoy",
        "unit": "percent",
    },
    {
        "symbol": "US_GOVT_2Y",
        "name": "美国国债收益率2年",
        "source_field": "美国国债收益率2年",
        "exchange": "US",
        "observation_type": "bond_yield",
        "unit": "percent",
    },
    {
        "symbol": "US_GOVT_5Y",
        "name": "美国国债收益率5年",
        "source_field": "美国国债收益率5年",
        "exchange": "US",
        "observation_type": "bond_yield",
        "unit": "percent",
    },
    {
        "symbol": "US_GOVT_10Y",
        "name": "美国国债收益率10年",
        "source_field": "美国国债收益率10年",
        "exchange": "US",
        "observation_type": "bond_yield",
        "unit": "percent",
    },
    {
        "symbol": "US_GOVT_30Y",
        "name": "美国国债收益率30年",
        "source_field": "美国国债收益率30年",
        "exchange": "US",
        "observation_type": "bond_yield",
        "unit": "percent",
    },
    {
        "symbol": "US_GOVT_10Y_2Y",
        "name": "美国国债收益率10年-2年",
        "source_field": "美国国债收益率10年-2年",
        "exchange": "US",
        "observation_type": "yield_spread",
        "unit": "percentage_point",
    },
    {
        "symbol": "US_GDP_YOY",
        "name": "美国GDP年增率",
        "source_field": "美国GDP年增率",
        "exchange": "US",
        "observation_type": "gdp_yoy",
        "unit": "percent",
    },
)
