server:
  host: 0.0.0.0
  port: 18000
  access_log: false
logging:
  enabled: true
  level: INFO
  format: json
  output: file # options: stdout|stderr|file (if 'file', file_config applies)
  include_caller: true
  file_config:
    dir: ./logs
    filename: artemis
  rotate_config:
    enabled: true
    rotate_interval: 1d # unit decides suffix pattern automatically (m->YYYYMMDDHHMM)
    max_age: 72h
    cleanup_enabled: true
telemetry:
  enabled: true
  service_name: artemis
  sampling: always
  otlp:
    protocol: http   # http | grpc
    endpoint: #http://localhost:4318/v1/traces
    headers: {}
    timeout_ms: 5000
    # insecure only used for grpc; ignored for http
http_client:
  timeout_seconds: 5
  verify_ssl: true
  headers: {}

dept_services:
  cronjob:
    host: "127.0.0.1"  # Artemis 回传进度/结果的 CronJob 服务地址
    port: 9999
  phoenixA:
    host: "127.0.0.1"          # 依赖的 phoenixA 服务地址（按需配置）
    port: 18085

sdk:
  baostock:
    idle_timeout: 300
  amazing_data:
    idle_timeout: 300
    username: "user"
    password: "password"
    host: "127.0.0.1"
    port: 9000
  mairui:
    license: ""

data_options:
  asset_types:
    - { value: "stock", label: "股票" }
    - { value: "index", label: "指数" }
  markets:
    - { value: "zh_a", label: "A股" }
  periods:
    - { value: "daily", label: "日线" }
    - { value: "weekly", label: "周线" }
    - { value: "5min", label: "5分钟" }
    - { value: "15min", label: "15分钟" }
    - { value: "30min", label: "30分钟" }
    - { value: "60min", label: "60分钟" }
  adjust_rules:
    - asset_type: "stock"
      options:
        - { value: "nf", label: "不复权" }
        - { value: "qfq", label: "前复权" }
        - { value: "hfq", label: "后复权" }
    - asset_type: "index"
      options: []

engine:
  task_engine:
    worker_task_timeout: 180
    amazing_data_cache_dir: "../cache/artemis/amazing_data"
  cache_engine:
    enabled: true
    cache_dir: "../cache/artemis"
    max_cache_size: "5GB"
    eviction_policy: "lru"
    eviction_check_interval: 100
    partition_rules:
      - match:
          asset_type: "stock"
          period: "daily"
        granularity: "yearly"
      - match:
          asset_type: "stock"
          period: "weekly"
        granularity: "yearly"
      - match:
          asset_type: "stock"
          period: "1min"
        granularity: "monthly"
      - match:
          asset_type: "stock"
          period: "5min"
        granularity: "monthly"
      - match:
          asset_type: "stock"
          period: "15min"
        granularity: "monthly"
      - match:
          asset_type: "stock"
          period: "30min"
        granularity: "monthly"
      - match:
          asset_type: "stock"
          period: "60min"
        granularity: "monthly"
      - match:
          asset_type: "index"
        granularity: "yearly"
      - match: {}
        granularity: "yearly"
