#!/usr/bin/env python3
"""
从现有的 JSONL 文件重新生成 SQL seed migration
"""
import json
from pathlib import Path
from typing import Any


def sql_string(s: str | None) -> str:
    if s is None:
        return "NULL"
    escaped = s.replace("'", "''")
    return f"'{escaped}'"


def sql_number(n: int | float | None) -> str:
    if n is None:
        return "NULL"
    return str(n)


def sql_bool(b: bool) -> str:
    return "TRUE" if b else "FALSE"


def sql_json(arr: list[Any]) -> str:
    if not arr:
        return "'[]'::jsonb"
    return f"'{json.dumps(arr, ensure_ascii=False)}'::jsonb"


def write_seed_migration(
    path: Path,
    datasets: list[dict],
    fields: list[dict],
    enums: list[dict],
) -> None:
    contract_version = fields[0]["contract_version"] if fields else "2026-06-25"
    lines = [
        "-- ============================================================",
        "-- 0004_govern_seed.sql",
        "-- ============================================================",
        "-- Generated by regenerate_seed_sql.py from scripts/field_dictionary/amazing_data/*.jsonl",
        "--",
        "-- This file inserts data rows into dictionary tables created by",
        "-- 0003_govern.sql (govern layer).",
        "-- ============================================================",
        "",
        f"DELETE FROM govern.data_field_dictionary WHERE source = 'amazing_data' AND contract_version = '{contract_version}';",
        f"DELETE FROM govern.data_enum_dictionary WHERE source = 'amazing_data' AND contract_version = '{contract_version}';",
        f"DELETE FROM govern.data_dataset_dictionary WHERE source = 'amazing_data' AND contract_version = '{contract_version}';",
        "",
    ]

    dataset_cols = (
        "contract_version, source, dataset, label_zh, data_types, storage_table, "
        "storage_tablespace, dictionary_tablespace, source_doc"
    )
    dataset_values = []
    for row in datasets:
        dataset_values.append(
            "("
            + ", ".join(
                [
                    sql_string(row["contract_version"]),
                    sql_string(row["source"]),
                    sql_string(row["dataset"]),
                    sql_string(row["label_zh"]),
                    sql_json(row["data_types"]),
                    sql_string(row["storage_table"]),
                    sql_string(row["storage_tablespace"]),
                    sql_string(row["dictionary_tablespace"]),
                    sql_string(row["source_doc"]),
                ]
            )
            + ")"
        )
    lines.extend([f"INSERT INTO govern.data_dataset_dictionary ({dataset_cols}) VALUES", ",\n".join(dataset_values) + ";", ""])

    field_cols = (
        "contract_version, source, dataset, data_type, data_type_label_zh, sdk_section, sdk_function, "
        "raw_field, canonical_field, label_zh, description, value_type, source_value_type, unit, scale, "
        "enum_ref, storage_location, is_metadata, is_core, comp_type_scope, aliases, source_doc, "
        "source_path, review_status, deprecated"
    )
    field_values = []
    for row in fields:
        field_values.append(
            "("
            + ", ".join(
                [
                    sql_string(row["contract_version"]),
                    sql_string(row["source"]),
                    sql_string(row["dataset"]),
                    sql_string(row["data_type"]),
                    sql_string(row["data_type_label_zh"]),
                    sql_string(row["sdk_section"]),
                    sql_string(row["sdk_function"]),
                    sql_string(row["raw_field"]),
                    sql_string(row["canonical_field"]),
                    sql_string(row["label_zh"]),
                    sql_string(row["description"]),
                    sql_string(row["value_type"]),
                    sql_string(row["source_value_type"]),
                    sql_string(row["unit"]),
                    sql_number(row["scale"]),
                    sql_string(row["enum_ref"]),
                    sql_string(row["storage_location"]),
                    sql_bool(row["is_metadata"]),
                    sql_bool(row["is_core"]),
                    sql_string(row["comp_type_scope"]),
                    sql_json(row["aliases"]),
                    sql_string(row["source_doc"]),
                    sql_string(row["source_path"]),
                    sql_string(row["review_status"]),
                    sql_bool(row["deprecated"]),
                ]
            )
            + ")"
        )
    lines.extend([f"INSERT INTO govern.data_field_dictionary ({field_cols}) VALUES", ",\n".join(field_values) + ";", ""])

    enum_cols = "contract_version, source, enum_name, code, label_zh, description, sort_order, source_doc, review_status, deprecated"
    enum_values = []
    for row in enums:
        enum_values.append(
            "("
            + ", ".join(
                [
                    sql_string(row["contract_version"]),
                    sql_string(row["source"]),
                    sql_string(row["enum_name"]),
                    sql_string(row["code"]),
                    sql_string(row["label_zh"]),
                    sql_string(row["description"]),
                    sql_number(row["sort_order"]),
                    sql_string(row["source_doc"]),
                    sql_string(row["review_status"]),
                    sql_bool(row["deprecated"]),
                ]
            )
            + ")"
        )
    lines.extend([f"INSERT INTO govern.data_enum_dictionary ({enum_cols}) VALUES", ",\n".join(enum_values) + ";", ""])

    path.write_text("\n".join(lines), encoding="utf-8")


def read_jsonl(path: Path) -> list[dict]:
    rows = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def main():
    project_root = Path(__file__).resolve().parents[3]
    out_dir = Path(__file__).resolve().parent
    migration_dir = project_root / "migrations" / "postgresql" / "security"

    financial_rows = read_jsonl(out_dir / "financial_statement.fields.jsonl")
    corporate_rows = read_jsonl(out_dir / "corporate_action.fields.jsonl")
    equity_rows = read_jsonl(out_dir / "equity_structure.fields.jsonl")
    enums = read_jsonl(out_dir / "enums.jsonl")
    datasets = json.loads((out_dir / "datasets.json").read_text(encoding="utf-8"))

    write_seed_migration(
        migration_dir / "0004_govern_seed.sql",
        datasets,
        financial_rows + corporate_rows + equity_rows,
        enums,
    )

    print("Regenerated seed migration:")
    print(f"  financial_statement fields: {len(financial_rows)}")
    print(f"  corporate_action fields: {len(corporate_rows)}")
    print(f"  equity_structure fields: {len(equity_rows)}")
    print(f"  enum values: {len(enums)}")
    print("Done!")


if __name__ == "__main__":
    main()
