FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata libc6-compat && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    rm -rf /var/cache/apk/*

WORKDIR /app

COPY phoenixa /app/phoenixa
COPY migrations /app/migrations
RUN mkdir -p /app/config
RUN mkdir -p /app/logs

RUN chmod +x /app/phoenixa

EXPOSE 8085

CMD ["/app/phoenixa", "-config=./config/config.yaml", "-env=production"]
